# Generated by Django 4.1.3 on 2022-12-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propesccao',
            fields=[
                ('pc_id', models.AutoField(primary_key=True, serialize=False)),
                ('pc_vendas', models.DecimalField(decimal_places=2, max_digits=19)),
                ('pc_conversao', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVendas',
            fields=[
                ('tp_id', models.AutoField(primary_key=True, serialize=False)),
                ('tp_nome', models.CharField(max_length=200)),
                ('data_registro', models.DateTimeField(verbose_name='data de registro')),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('vendas_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateTimeField(blank=True)),
                ('data_aceite_cliente', models.DateTimeField(blank=True, null=True, verbose_name='data')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=19)),
                ('tipo_venda', models.ForeignKey(db_column='tp_id', on_delete=django.db.models.deletion.DO_NOTHING, to='register.tipovendas')),
            ],
        ),
    ]
