# Generated by Django 4.1.3 on 2022-12-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propesccao',
            fields=[
                ('pc_id', models.AutoField(primary_key=True, serialize=False)),
                ('pc_vendas', models.DecimalField(decimal_places=2, max_digits=19)),
                ('pc_conversao', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.RenameField(
            model_name='tipovendas',
            old_name='nome',
            new_name='tp_nome',
        ),
    ]
